exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
lsi: false
pygments: true
safe: true

title: The Lens Library
tagline: Lenses, Folds and Traversals

author:
  name: Edward Kmett
  email: ekmett@gmail.com
  github: ekmett
  twitter: kmett

production_url: http://lens.github.com
